"""empty message

Revision ID: 49649f5d40c7
Revises: a24291e19243
Create Date: 2021-08-12 18:56:16.656809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49649f5d40c7'
down_revision = 'a24291e19243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
