"""empty message

Revision ID: a24291e19243
Revises: 7c12d3af296c
Create Date: 2021-07-26 23:11:32.893438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24291e19243'
down_revision = '7c12d3af296c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('content', sa.String(length=400), nullable=True))
    op.drop_column('tweet', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('text', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('tweet', 'content')
    # ### end Alembic commands ###
